:PROPERTIES:
:ID: E3AF70C3-DA8D-4CB9-9096-444A106714DB
:END:
#+title: Eigenfunctions of hermitian operators

Given a [[id:E5B1D38D-297B-4867-91DA-75156F747A92][Hilbert Space]], usually [[id:6685FCEC-5551-44BF-9E23-50CD4F65DEFC][L2]] for quantum mechanics, representing the states \(|\psi\rangle\) of a system. The determinate or pure states of the an observable \(Q\) (which is an operator over the Hilbert space) are the eigenfunctions of said \(Q\).

This eigenfunction fall into two important categories: - The spectrum is /discrete/ (i.e. the eigenvalues are separated from one another), then the eigenfunctions lie in the same Hilbert space and they constitute physically realizable states. - The spectrum is /continuous/ (i.e. the eigenvalues are dense an fill out an entire range), then the eigenfunctions are not normalizable, and they do not represent possible wave functions.

For example, the Hamiltonian for the harmonic oscillators only has a discrete spectrum, on the other hand, the free particle Hamiltonian only has a continuous spectrum. There are also operators, like the Hamiltonian for a finite square well, whose spectrum has a discrete part and a continuous part.

** Discrete spectra
Mathematically, the normalizable eigenfunctions of a hermitian operator have two important properties: 1. Their eigenvalues are real. 2. Eigenfunctions of distinct eigenvalues are orthogonal.

If the Hilbert space is finite-dimensional the eigenvectors have a crucial third property, they form a complete basis. This is usually taken as an axiom for the eigenfunctions of physically realizable observable in the \(L^2\) case.
