:PROPERTIES:
:ID:       BE1D3754-E483-4539-95E4-1848E738E053
:END:
#+title: Ética y Política

Para Aristóteles la Política es la ciencia arquitectónica del resto, ya que además de organizar la vida comunitaria es la que explica el lugar donde el resto de ciencias cobra sentido y adquiere su finción.

Aristíteles, tras arugmentar la naturaleza social de animal humano, declarará la *primacía ontológica de la ciduad frente al individuo*. También es interesante como el filósofo justifica la importancia del discurso es nuestra vidas políticas explicando que el huamano es retórico por naturaleza.


* Derechos

Los derechos en Aristóteles son siempre propios de una comunidad concreta, en su caso de una polis concreta. Esto explica porque pueden existir seres intelectivos pero sin derechos dentro de una ciudad, extranjeros, prisioneros o esclavos. No existe un derecho de la igualdad de lo humano, porque lo humano siempre es abstracto, solamente hay un derecho de la igualdad de lo común, porque es aquí donde cada uno tiene capacidad para intervenir.


* Formas de gobierno

Dentro de una comunidad natural, que forme una comunidad de lenguaje y una comunidad de comprensión, existen distintas opciones de acción natural para legislarse y organizarse. De nuevo, entendiendo el registro pragmático de toda la forma de ciencia platónica. Este carácter contingente de la forma de vida se justifica perfectamente en el hecho de que todas ellas pueden ponerse al servicio de la comunidad.

Hay tres formas de gobierno con sus tres respectivas corrupciones: monarquía/tiranía, aristocracia/oligarquía, democracia/demagogia. Ahora bien, aunque todas ellas pueden ser buenas y naturales, Aristóteles prefiere, en virtud de que es más provechosa, la democracia regida por leyes, es decir, la politeia.

De esta contingencia de las formas de gobierno se explica que no encontremos una ley sustantiva en Aristóteles, siempre se explica la ley como arquitectónica. Si el monarca es bueno y sirva a su comunidad todo estará bien, simplemente que es más sencillo alcanzar esta situación en una democracia.


* Felicidad como fin

Cual es la acción que pone en marcha todo el mecanismo intelectivo, ontopraxiológico, que pone en marcha la razón humana. Para Platón esto sería la visión del Bien, y todo su sistema político se crea entorno a esta idea. En Aristóteles el fin último de la vida humana será la felicidad.

Entonces, supuestas las posiciones ontológicas de la vida humano, y la política es una condición ontológica al ser natural, como podemos alcanzar el fin último de la felicidad. Este es el punto de inicio de la ética aristotélica, tras haber establecido todo el programa arquitectónico de entendimiento de la naturaleza, y con el objetivo de perseguir la felicidad. 

Es imprescindible entender que el *hedonismo no es la búsqueda de placeres*.


* La virtud de la sabiduría

Por nuestra constitución natural, cuya raíz es ontológica, por la búsqueda del conocimiento cabe considerar a la sabiduría como una virtud. La sabiduría trae felicidad.
