:PROPERTIES:
:ID: 6E292AE0-8DB0-4313-B824-37023788E8AD
:END:
#+title: 3. Los Niveles de Conocimiento

* Estética Trascendental
Kant aporta los siguientes argumentos para probar que espacio y tiempo son formas a priori de la sensibilidad, y no conceptos en la mente: 1. Las ideas de espacio y tiempo no pueden ser product de una abstracción (a partir de un material recibido a posteriori), porque, para abstraer con la mente a la representación de espacio y tiempo de la yuxtaposición de los cuerpos o de la iteración de los hechos, tenemos que tener ya las representaciones de espacio y tiempo; 2. Espacio y tiempo son representaciones que tenemos siempre y de las que no podemos despojarnos. No podemos representarnos los seres y el mundo sin la representación de espacio y tiempo. Pero lo que siempre tenemos que tener y es, por tanto, necesario, es a priori; 3. No son representaciones universales, sino singulares y únicas. Espacios y tiempos son sólo secciones cuantitativas del único espacio y del único tiempo. 4. Espacio y tiempo son infinitos: los espacios particulares están en el espacio, y lo mismo hay que decir del tiempo

De lo anterior se concluye que el espacio y tiempo no son propiedades de las cosas, sino las formas, externa e interna, de nuestra sensibilidad y, por tanto, las condiciones subjetivas que hacen posible nuestras percepciones de los fenómenos.

* Analítica Trascendental
En la Analítica Trascendental Kant aborda la crítica de la facultad del conocimiento intelectual, o sea, el entendimiento. Mientras los sentidos configuran intuiciones, percepciones o representaciones a partir de las impresiones que recibimos pasivamente, el entendimiento actúa sobre esas intuiciones o representaciones, las organiza y configura con ellas el objeto del conocimiento.
