:PROPERTIES:
:ID: 3241B482-B4C5-47DC-85CA-9B7F443081C4
:END:
#+title: 6. Duns Scoto

* Voluntarismo
Duns Scoto defiende la originalidad del individuo y la importancia de la voluntad. En primer lugar, sostiene que la voluntad es siempre anterior al intelecto. Aunque el intelecto pueda, evidentemente, influir en la voluntad, es la voluntad la que manda al intelecto provocando su acto.

Frente a la doctrina de Avicena, que consideraba los seres finitos como emanados del Ser necesario por vía de la necesidad, Duns Scoto considera que lo posible procede de lo necesario por un acto de libertad. Scoto insiste en la libertad de la voluntad divina, oponiéndose tanto al determinismo arábico como al pensamiento de Sto. Tomás. Por un lado, Avicena y Averroes defendían la idea aristotélica de la voluntad como carencia, ya que solo se desea aquello que de lo que se carece. Y Sto. Tomás defendía, como Scoto, una cierta voluntad divina, pero subordinándola a la sabiduría divina al sólo crear Dios aquello que reconoce como bueno en su sabiduría.

Santo Tomás, a su vez, veía en la voluntad algo determinado por el conocimiento de lo bueno. Esto es, es el entendimiento el que ofrece opciones a la voluntad, expresando en cada caso lo que es bueno y determinando así a esta. La libertad, así, es aquella necesidad que parte de la esfera del saber. Este determinismo intelectualista se hace tan extremo en Godofredo de Fontaines que acaba por convertir la mera representación sensible en causa eficiente de la actividad volitiva.

Frente a estas ideas, Scoto responde que en tal caso se hace inexplicable la contingencia de las funciones volitivas. Si el proceso natural "conocer lo bueno-quererlo" se encuentra unívocamente determinado, entonces no hay elección para ni, hablando propiamente, libertad. Ahora bien, sólo en la contingencia hay responsabilidad. Se puede mantener ésta solo cuando se reconoce que el entendimiento no ejerce una influencia determinante sobre la voluntad.

Este indeterminismo enseñado por Duns Scoto ve en la voluntad la fuerza radical del alma y, dando la vuelta a la tesis tomista, considera que la voluntad es la que determina, de hecho, el curso de la actividad racional. Entonces, el proceso del entendimiento parte del conjunto de representaciones, más o menos confusas e imperfectas, que el individuo tiene como contenidos de conciencia. De éstas representaciones tan sólo se convierten en claras y perfectas aquellas a las que dirige su atención la voluntad, no determinada por otro hecho, en este proceso, por sí misma. La voluntad intensifica luego estas representaciones que ha elevado de su estado confuso a su estado de claridad, perdiéndose aquellas otras a las que la voluntad no prestó atención. De este modo, por tanto, puede decirse que es la voluntad la que, en efecto, determina la actividad cognoscitiva y racional de los individuos.
