:PROPERTIES:
:ID: 2A0946D9-C3E9-4839-AC7F-DA38835A6D07
:END:
#+title: 5. Eclecticismo

--------------

aliases: - Empédocles
---

* Empédocles
fl. h. 450

Escribió dos poemas, en dialecto jónico, cuyas diferencias de estilo y carácter han dado origen al llamado "enigma de Empédocles". En el /Poema sobre la Naturaleza/ trata el problema cosmológico de manera similar a sus contemporáneos. En /Purificaciones/ el estilo es más florido, rico en metáforas y epítetos altisonantes, presentándose como un taumaturgo o como un dios. El carácter de este último puede explicarse por una crisis moral del filósofo al ser derribado del poder y desterrado. Aunque hay autores que sostienen lo contrario, afirmando que /Purificaciones/ fue primero y que, tras ser desterrado, se interesó más por la filosofía positivista.

La doctrina de este autor equivale a una tentativa ecléctica de fundir en una síntesis las distintas tendencias de su tiempo. En su sistema incorpora nociones, jónicas, pitagóricas, eleáticas y de Heráclito, además de aspiraciones místicas y morales semejantes a los órficos. En sus cuatro "raíces de las cosas" integra el agua de Tales, el aire de Anaxímenes, la tierra de Jenófanes y el fuego de Heráclito. Combina el ser inmóvil de Parménides con el ser de de Heráclito en perpetua transformación, tratando de salvar a la vez la undiad permanente del ser y la pluralidad de las cosas particulares.

** El poema "Sobre la Naturaleza"
Empieza con una pomposa introducción que recuerda a Parméndies.

*** Gnoseología
Da importancia al testimonio de los sentidos. Afirmando que ni ellos ni la razón por separado son suficientes para alcanzar la verdad, ambos serían necesarios.

*** Física
1. *Las cuatro raíces*. Concibe el ser como eterno e indestructible. Integrado este por cuatro "raíces", las cuales identifica con nombre de Dioses (aunque los Dioses también estarían conformados por ellas). Estas cuatro tendrán importancia e irán unidas a su nombre hasta su destrono por la Química moderna en el siglo XVIII.
2. Junto a las cuatro raíces Empédocles señala dos fuerzas fundamentales, cósmicas, eternas y antagónicas: *el Amor y el Odio*, que actúan sobre los elementos agrupándolos y disgregándolos en un proceso cíclico, dominado por "el vasto y antiguo juramento de la intolerable necesidad".
3. El ciclo del Gran Año se sucede alternando ciclos donde predomina la fuerza del Amor, provocando la uniendo de las raíces en un ser único y compacto a la forma de Parménides; y ciclos donde predomina el Odio, de donde nace la pluralidad de las cosas.
4. De la victoria parcial de ambos en cada momento surgen cosas plurales pero no totalmente, formando entes hechos por partes como los animales. En primera instancia estas partes aparecerían unidas aleatoriamente, aunque en otras partes del poema se habla de afinidades como el aceite y el agua. En está unión arbitraria hasta formas seres complejos podemos ver algo de la cosmología que en la física moderna idearía Bolztman.

*** Antropología
El hombre se compone de una mezcla proporcionada de los cuatro elementos. Empédocles ejerció de médico dandole importancia a la armonía y balance entre los cuatro elementos.

En el poema hace una alusión al hilozoísmo universal al decir: "todas las cosas tienen entendimiento y pensamiento".

** El poema de las "Purificaciones"
Se presenta como un taumaturgo divino, no como un filósofo.

*** Orfismo
Presenta muchos elementos de carácter órfico y pitagórico, la preexistencia de las almas, el pecado, la caída del hombre de un estado celeste feliz, el pesimismo sobre la existencia del hombre, la transmigración de las almas.

Aunque probablemente la influencia órfica la obtenga a través de las enseñanzas pitagóricas.

*** Pesimismo
En este poema domina un concepto pesimista de la existencia actual. El alma, caída del estado feliz primitivo, se encuentra lejos de su patria, encerrado en un cuerpo material, en un país extraño dominado por la Discordia y por las luchas sangrientas.

*** La transmigración
La infelicidad del estado presente se agrava por la transmigración de las almas, que andan vagando de unos cuerpos en otros con sujeción a ciclos más o menos prolongados. La transmigración tiene un carácter expiatorio, como de ley regida por la Necesidad.

*** La liberación
Las "Purificaciones" termina con una doctrina de la salvación. Aunque, a diferencia de la órfica, está no trata de la omofagia, iniciación y expulsión de los elementos titánicos. Aquí la purificación llega en tres etapas, primero se ha de llegar a ser médico, poeta y adivino; luego alcanzar el nivel de héroe; y, por último, ser deificado.
