:PROPERTIES:
:ID: 062CDA1E-B03D-46A2-AA0B-A6E0F7577DA6
:END:
#+title: 1. Vida y carácter

La juventud de Sócrates coincide con el esplendor de la Atenas de Pericles. Las victorias militares, la hegemonía dentro de la liga de Delos, el triunfo del partido democrático y el fin de la piratería. Llegando la gloria ateniense a su fin con la guerra del Peloponeso, Sócrates pelea en varias batallas y ejerce de patriota durante toda su duración.

Durante sus primeros años de formación intelectual aprende la física presocrática y se introduce en la filosofía escuchando las lecciones de Arquelao, discípulo de [[id:02332673-D764-4E02-B708-3279AC3E50B7][Anaxágoras]]. Pero pronto se desengaña de aquellas especulaciones, consagrándose la estudio de los problemas del hombre, en cuanto a ciudadano, considerándolos como los más urgentes en la Atenas de su tiempo. En palabras de Cicerón, esto hace bajar a la Filosofía del cielo a la tierra.

Reflexionando sobre las causas de la ruina de Atenas, Sócrates adopta una actitud frente a los filósofos y los sofistas negativa. Poco podían importarle los principios de las cosas, ni las frívolas exquisiteces de aquellos retóricos ambulantes. El hombre que le interesa a Sócrates no es el hombre en abstracto, sino en concreto, el ciudadano ateniense.
