:PROPERTIES:
:ID: CC3C5498-C630-416E-B0E2-79CA1281B1D1
:END:
#+title: 1. Francis Bacon

El mérito atribuible a Bacon no es tanto el desarrollo de un método científico, sino su confianza en la ciencia como instrumento de dominio y transformación de la naturaleza, así como sus críticas a la filosofía anterior por estar demasiado centrada en discusiones conceptuales y altamente especulativas.

Bacon defiende, contra la deducción aristotélica, el método inductivo como verdadera base de la ciencia. Este cambio de paradigma esta motivado por la visión práctica que tenía Bacon de la ciencia, contraponiéndose a la ciencia teórica centrada en la busca de la verdad de Aristóteles. Bacon, además, critica la falta de rigor y sistematización en el uso de la inducción que llevaban a cabo los aristotélicos.

Esta posición centrada en la recogida sistemática de datos será la que, con el tiempo, se mostrará inferior al método galileico de la formulación de hipótesis, deducción y experimento. Bacon no supo ver la importancia de la modelización matemática en la ciencia. De ahí, que su mayor avance sea el conceptual, de la ciencia teórica a la práctica, que metodológico, con sus tablas inductivas.

Bacon también trabaja en buscar la causa de los errores en el conocimiento, que lo llevará a un concepto temprano de los sesos cognitivos, a los que llamará ídolos.
