:PROPERTIES:
:ID: 605A9A8C-E467-4375-9C52-E45F7C8DDE79
:END:
#+title: Cauchy's Integral Formulas

** Cauchy's Integral Formula
Let \(f(z)\) by [[id:3C67CDAF-C6A1-459F-8733-49487370C514][analytic]] inside and on a simple closed curve \(C\) and let \(a\) be any point inside \(C\). Then
\[
f(a) = \frac{1}{2\pi i}\oint_C \frac{f(z)}{z-a}\,dz
\]
where \(C\) is traversed in the positive sense.
Also, the \(n\)th derivative of \(f(z)\) at \(z = a\) is given by
\[
f^{(n)}(a) = \frac{n!}{2\pi i} \oint_C \frac{f(z)}{(z-a)^{n+1}}\,dz \quad n = 1, 2, 3, ...
\]

** Some important corollaries
*** Morera's Theorem (converse of [[id:4DA6688C-4D0F-4226-83D0-AF291D3F4B05][Cauchy's Theorem]])
If \(f(z)\) is continuous in a [[id:886F9E7C-95BA-437B-977F-637686061F7E][simply-connected]] region \(\mathcal{R}\) and if \(\oint_C f(z)\,dz = 0\) around every simple closed curve \(C\) in \(\mathcal{R}\), then \(f(z)\) is analytic in \(\mathcal{R}\).

*** Cauchy's Inequality
Suppose \(f(z)\) analytic inside and on a circle \(C\) of radius \(r\) and center at \(z = a\). Then
\[
|f^{(n)}| \leq \frac{M\cdot n!}{r^n} \quad n = 0, 1, 2, ...
\]
​### Liouville's Theorem
Suppose that for all \(z\) in the entire complex plane, (i) \(f(z)\) is analytic and (ii) \(f(z)\) is bounded, i.e. \(|f(z)| < M\) for some constant \(M\). Then \(f(z)\) must be a constant.

*** Fundamental theorem of algebra
Every polynomial equation \(P(z) = a_0 + a_1z + a_2z^2 + ...  + a_nz^n = 0\) with degree \(n \geq 1\) and \(a_n \neq 0\) has at least one root.
From this it follows that \(P(z) = 0\) has exactly \(n\) roots, due attention begin paid to multiplicities of roots.

*** Gauss' mean value theorem
Suppose \(f(z)\) is analytic inside and on a circle \(C\) with center at \(a\) and radius \(r\), Then \(f(a)\) is the mena of the values of \(f(z)\) on \(C\), i.e.,
\[
f(a) = \frac{1}{2\pi}\int_0^{2\pi} f(a+re^{i\theta})\,d\theta
\]

*** Maximum modulus theorem
Suppose \(f(z)\) is analytic inside and on a simple closed curve \(C\) and is not identically equal to a constant. Then the maximum value of \(|f(z)|\) occurs on \(C\).
​### Minimum modulus theorem
Suppose \(f(z)\) is analytic inside and on a simple closed curve \(C\) and \(f(z) \neq 0\) inside \(C\). Then the maximum value of \(|f(z)|\) occurs on \(C\).
