:PROPERTIES:
:ID: 02332673-D764-4E02-B708-3279AC3E50B7
:END:
#+title: 6. Pluralismo heterogéneo

--------------

aliases: - Anaxágoras
---

* Anaxágoras
fl. h. 460

Fue el primer filósofo que abrió escuela en Atenas. Entre sus oyentes figuraron Eurípides, Protágoras, Tucídides, Mirón y Fidias.

Fue un ejemplo perfecto de sabio jónico. Cosmopolita individualista, desarraigado de la metrópoli e indiferente a la patria. Se intesaba por la ciencia, sin preocupaciones morales ni religiosas, lo que lo llevo a su encarcelamiento en Atenas de la que acaba huyendo por consejo de su amigo Pericles. Gozó de gran reputación como físico, matemático y astrónomo, llegando a ser llamado el /fisicísimo/ por Sexto Empírico. Se le atribuye un tratado /Sobre los escenarios/, un libro sobre la cuadratura del círculo, escrito en la cárcel, y una obra de tres libros /Sobre la naturaleza/.

* Física
** El problema
Anaxágoras se enfrenta al modo jónico con el problema de la unidad y la pluralidad de las cosas. Marca un avance importante aunque no original, al admitir un doble principio, uno pasivo y inerte, masa caótica en que están mezclados todos los elementos; y otro activo, motor, inteligente, regulador del cosmos, causa de la unidad y del movimiento. No está claro si hay que entender esto en el sentido dualista de materia y espíritu. Más bien parece que también la Mente tiene un sentido Material

** Las "homeomerías"
Anaxágoras adopta la posición de Parménides frente al problema del origen de las cosas: "De la nada, nada sale. Todo sale del ser". Su solución es "Todo está en todo". Esto es posible porque la materia es divisible hasta el infinito (contra Leucipo). Los elementos no son cuatro, como en Empédocles, sino tantos como especies de distintas de cosas (agua, aire, etc). Son una especie de polvo sutilísimo, infinitos, inalterables, indestuctribles, pasivos. Son las "semillas" de todas las cosas.Ha prevalecido la palabra "homeomerías", empleada por Aristóteles.

Las cosas se producen por /agrupación/ y /disgregación/.

** Formación del cosmos
En el comienzo todo estaba mezclado y confuso en el caos de los elementos. Estos existieron desde toda la eternidad, distintos pero unidos en la unidad del Ser. A su vez, existía la Mente (νοῦς), infinita libre, potentísima, purísima y no mezclada, inteligentísima y conocedora de todas las cosas. Aunque unos atributos tan elevados parecen propios de la divinidad, no obstante la Mente de Anaxágoras no es un Dios trascendente, sino una fuerza cósmica, a la manera del Logos de Heráclito, o el Amor y la Discordia de Empédocles. Su misión no es creadora, ni siquiera ordenadora, puesto que todos los elementos son eternos, sino solamente impulsora del movimiento del torbellino cósmico para vender la inercia de la materia, iniciando la disgregación de las homeomerías. Tras este momento inicial, Anaxágoras, como le reprocha Aristóteles, no la utiliza para nada.

Anaxágoras permanece todavía dentro de la línea de los físios jonios. Considera la materia como inerte, y acude, como Empédocles, a una fuerza extrínseca, para explicar el movimiento y la división de las cosas. Su Mente no pasa de fuerza cósmica ordenadora. Pero preludia el Demiurgo de Platón y contribuye a preparar el Νόησις Νοήσεως de Aristóteles, elevando un poco el tono demasiado materialista de las cosmogonías presocráticas.

* Bibliografía
[cite/t:@FraileGuillermo1975Hdlf]
