:PROPERTIES:
:ID: 19C465CE-15FC-454C-BE90-A4103184302E
:END:
#+title: 5. Santo Tomás

La doctrina tomista supondrá una importantísima adaptación de la metafísica aristotélica a la posición cristiana. La principal reforma consistirá en la diferenciación entre esencia y existencia. Mientras que Aristóteles identifica potencia con materia, y acto con forma, Sto. Tomás las agrupa afirmando, además, que la existencia es el acto de la esencia. El único ser donde esencia y existencia forman un uno es Dios, y el resto de seres serán esencias (en la mente de Dios) llevados a la existencia por el mismo (Dios la /Causa esendi/). De esta forma se adapta la idea de la necesidad aristotélica de los seres (al ser esencia y existencia un mismo concepto) a la concepción cristiana de la creación.

Al separar esencia y existencia, Sto. Tomás puede distinguir entre el ser de Dios y el ser de las criaturas. El ser donde esencia y existencia se identifican será como es Dios, mientras que las criaturas contingentes, con esencia necesaria, pero existencia contingente serán como las criaturas.
