:PROPERTIES:
:ID: 43462517-A16E-4E88-B6F6-F5F7C70F1BCB
:END:
#+title: 7. Ockham

Ockham dirige una crítica radical contra el realismo, tras realizar su análisis del formalismo de Duns Scoto y tras su discusión con el realismo moderado de Sto. Tomás.

El punto de partida del pensamiento de Ockham es el principio según el cual no se tiene conocimiento de nada si no es a través de un acto de experiencia. A partir de este principio se distinguen dos tipos de conocimiento:

1. Conocimiento intuitivo: es el que nos proporciona con toda evidencia el saber si algo existe o no. O dicho de otro modo, es el que permite al entendimiento juzgar acerca de la realidad o irrealidad del objeto. Se subdivide en:
   - Perfecto: cuando su objeto es un ser o un hecho actual y presente. Este conocimiento recibe el nombre de experiencia en Ockham.
   - Imperfecto: cuando versa sobre un objeto o un hecho pasado, o sea, derivado de una experiencia anterior.
   - Intelectual: cuando sus objetos son los hechos o estados de la experiencia interna.
2. Conocimiento abstracto: es el que no tiene en cuenta la realidad o irrealidad del objeto. Tiene siempre su origen en el conocimiento intuitivo.

* Controversia de los universales
Ockham niega radicalmente la posibilidad del realismo de los universales. Los conceptos son sólo actos del entendimiento en virtud de los cuales éste tiende más allá de sí mismo hacia una realidad por conocer.

Para Ockham el valor del concepto, su relación con la entidad a la que se refiere, radica en su origen, o sea, en como significa la realidad a la que remite. Por significar entiende la referencia del signo a una realidad distinta de sí. Esta función significativa se lleva a cabo en diferentes niveles: 1. En el nivel de significación representativa, donde se produce tanto un conocimiento del signo con el que se representa como un conocimiento de la cosa significada o representada en el estricto sentido del término. 2. En el nivel de significación lingüística, donde, junto a la característica de la función significativa como generadora de intelección, se da en el signo la característica esencial que es su capacidad de suposición.

Es, por tanto, la función suposicional -la capacidad del signo de estar en lugar de la cosa y representarla- la que hace que los signos coincidan con la noción de término. En suma, los conceptos son un tipo de signos proposicionales, de los que otro tipo de palabras, verba, que ejercen su función comunicativa como elementos de un lenguaje. Concretamente, Ockham distingue tres tipos de signos representativos o términos, y establece entre ellos una relación jerárquica de subordinación: 1. Signos escritos: son signos de palabras. 2. Palabras: son signos de conceptos. 3. Conceptos: son intenciones o afecciones del entendimiento.

* La teoría de la suppositio
En el pensamiento de Ockham, la /suppositio/ es la propiedad que los términos o signos lingüísticos tienen de reemplazar a los objetos y ocupar su puesto en la predicación proposicional. Es decir, la /suppositio/ es la dimensión semántica de los términos en las proposiciones, la referencia de los términos a objetos diversos como cosas, personas a otros términos. 1. La suposición personal: cuando los términos están en lugar de las cosas significadas por ellos. /E.g./ "el hombre es animal". 2. La suposición simple: cuando el término está en lugar del concepto. /E.g./ "hombre es una especie". 3. La suposición material: cuando el término no es empleado en su significado, sino como signo verbal o escrito. O dicho de otro modo, cuando el término reemplaza, no a un signo natural, sino arbitrario. /E.g./ "hombre es un nombre".

La gran novedad en Ockham con respecto a la teoría de la suppositio radica en aplicarla no solamente a los signos arbitrarios (orales o escritos), sino también a nivel del concepto. Convierte a la suppositio en una propiedad proposicional, elevando así el planteamiento del problema del conocimiento desde el nivel atómico del concepto, al nivel molecular de la proposición. Ya que si la validez de un concepto viene dado por su capacidad supositiva no llegará con preocuparse de los términos, sino que habrá de analizar las proposiciones donde representan y suposicionan.

* Empirismo
Ockham se adelanta a Locke y a Hume en lo siguiente: 1. La sustancia no puede ser conocida sino a través de sus accidentes. Por tanto, no tenemos de ella sino un conocimiento negativo. La sustancia, dice ya Ockham, es "el sustrato desconocido de las cualidades que nos muestra la experiencia". 2. La relación causa-efecto no tiene validez científica, pues del conocimiento de un fenómeno no podemos deducir el conocimiento de otro que sea su causa o su efecto. Causa y efecto requerirían ser conocidas cada uno mediante actos de experiencia independientes y directos.
