:PROPERTIES:
:ID: BF626A1A-76F1-426B-96BF-15B2A85C14F5
:END:
#+title: README

* Custom controls
This plugin allows to add responsive custom controls to reveal.js which allow arbitrary positioning, layout, and behaviour of the controls.

[[https://rajgoel.github.io/reveal.js-demos/customcontrols-demo.html][Check out the live demo]]

** Installation
Copy the files =plugin.js= and =style.css= into the plugin folder of your reveal.js presentation, i.e. =plugin/customcontrols= and load the plugin as shown below.

#+begin_src html
<link rel="stylesheet" href="plugin/customcontrols/style.css">
<script src="plugin/customcontrols/plugin.js"></script>

<script>
    Reveal.initialize({
        // ...
        plugins: [ RevealCustomControls ],
        // ...
    });
</script>
#+end_src

Note, without configuration you need to add

#+begin_src javascript
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
#+end_src

between =<head>= and =</head>= of your HTML file because the defaults use [[http://fontawesome.io/][Font Awesome]].

** Configuration
The plugin can be configured by adding custom controls and changing the layout of the slide number, e.g., by:

#+begin_src javascript
Reveal.initialize({
    // ...
  customcontrols: {
        controls: [
      {
              id: 'toggle-overview',
              title: 'Toggle overview (O)',
              icon: '<i class="fa fa-th"></i>',
              action: 'Reveal.toggleOverview();'
            },
            { icon: '<i class="fa fa-pen-square"></i>',
              title: 'Toggle chalkboard (B)',
              action: 'RevealChalkboard.toggleChalkboard();'
            },
            { icon: '<i class="fa fa-pen"></i>',
              title: 'Toggle notes canvas (C)',
              action: 'RevealChalkboard.toggleNotesCanvas();'
            }
        ]
    },
    // ...

});
#+end_src

The =id= and =title= are optional. The configuration should be self explaining and any number of controls can be added. The style file can be altered to control the layout and responsiveness of the custom controls.

** License
MIT licensed

Copyright (C) 2020 Asvin Goel
