:PROPERTIES:
:ID: ABBE2CAB-E14B-48D0-BB46-A5D35CC15334
:END:
#+title: 3. Escuela Cínica

--------------

aliases: - cínicos - cínico
---

Atribuyeron a Antístenes la fundación de la escuela, para justificar su ascendencia socrática, aunque como verdadero fundador debe considerarse a su oyente Diógenes de Sínope.

* Antístenes
** Ontología
Negaba los conceptos universales y solamente admitía la realidad particular. El pensamiento se reduce a las palabras. De las cosas sólo puede decirse su nombre propio, que es único para cada una. Tampoco se le puede aplicar ningún predicado. Puede decir "el hombre es hombre", pero no "el hombre es bueno, malo", etc.

** Ética
La moral de Antístenes es una exageración del aspecto negativo de la doctrina de Sócrates. Se proponía el fin práctico de conseguir la felicidad, y la hacía consistir en una vida tranquila, lograda mediante el ejercicio de la virtud, que es el único bien.

Condenaba la guerra, las ambiciones y luchas entre ciudadanos.

* Diógenes
Es el verdadero padre del cinismo. Acentúo la indiferencia de Antístenes, convirtiéndola en desprecio de todas las convencionales y artificiales. Hacía gala de practicar una vida rigurosamente "natural", imitando a los animales, contraponiendo la vida de éstos y la de los bárbaros a la de los griegos.

Se mofaba de las ciencias, de las artes, de la religión y de todas las instituciones sociales. Sólo admitía la "educación" cínica, para los jóvenes, prudencia; para los viejos, consuelo; para los pobres riqueza, y para los ricos, ornato.

El cinismo no es un sistema filosófico, pues carece de fondo doctrinal positivo. Es más bien un movimiento esencialmente negativo, subversivo y demoledor, de oposición a todos los valores sociales y culturales. Más que filósofos, sus seguidores fueron agitadores populares, que combatían usando la ironía y el ingenio. Tampoco llegaron, claro está, a tener un carácter de movimiento proletario. Sus representantes eran considerados tipos pintorescos y extravagantes, y no se les tomó demasiado en serio.
