:PROPERTIES:
:ID: 062CDA1E-B03D-46A2-AA0B-A6E0F7577DA6
:END:
#+title: 1. Vida y carácter

La juventud de Sócrates coincide con el esplendor de la Atenas de Pericles. Las victorias militares, la hegemonía dentro de la liga de Delos, el triunfo del partido democrático y el fin de la piratería. Llegando la gloria ateniense a su fin con la guerra del Peloponeso, Sócrates pelea en varias batallas y ejerce de patriota durante toda su duración.

Durante sus primeros años de formación intelectual aprende la física presocrática y se introduce en la filosofía escuchando las lecciones de Arquelao, discípulo de [[id:02332673-D764-4E02-B708-3279AC3E50B7][Anaxágoras]]. Pero pronto se desengaña de aquellas especulaciones, consagrándose la estudio de los problemas del hombre, en cuanto a ciudadano, considerándolos como los más urgentes en la Atenas de su tiempo. En palabras de Cicerón, esto hace bajar a la Filosofía del cielo a la tierra.

En cuánto a su evolución ontológica cabe destacar que Sócrates es discípulo del último de los físicos jonios, Diógenes de Apolonio. Diógenes defiende el regreso a Tales y a Anaximandro, defiende dejar atrás la idea del ser y volver a la filosofía arcaica, es jonio arcaizante. Tras estudiar en su juventud esta física jonia, concretamente arcaizante,  acepta la crítica sofista y concluye que merece la pena mantener la identidad parminea pero aceptando que el responsable de la identidad entre pensar y el ser es el pensar. Podemos resumir este punto de vista diciendo que estamos instalados necesariamente en el pensar, y es desde él desde donde podremos reconstruir el ser.

Reflexionando sobre las causas de la ruina de Atenas, Sócrates adopta una actitud frente a los filósofos y los sofistas negativa. Poco podían importarle los principios de las cosas, ni las frívolas exquisiteces de aquellos retóricos ambulantes. El hombre que le interesa a Sócrates no es el hombre en abstracto, sino en concreto, el ciudadano ateniense.
