:PROPERTIES:
:ID: 06C79471-2FC1-4BA8-B597-9ED445DE1B62
:END:
#+title: 4. Doctrinas

--------------

aliases: - doctrinas socráticas
---

** La reflexión del hombre sobre sí mismo
Típicamente socrático es su insistente llamamiento a la interioridad, invitando al hombre a reflexionar sobre sí mismo. A la pretenciosa omnisciencia de los sofistas ("Preguntad..."), Sócrates opone modestamente su "sólo sé que no sé nada". El principio fundamenta de la sabiduría consisten, por una parte, en el reconocimiento de la propia ignorancia, pero al mismo tiempo en reflexionar sobre el propio yo para conocerse a sí mismo.

** Antropología
Sócrates parece haber tenido un concepto optimista y muy elevado de la naturaleza humana y de la dignidad del hombre, como un ser privilegiado entre todos los demás seres del mundo. Tiene razón, palabra y puede adquirir la ciencia.

Distingue entre cuerpo y alma. Esta es la parte mejor del hombre y de naturaleza divina. Compara la muerte a /un sueño sin sueños/, a una supervivencia del alma como una sombra sin sensaciones y sin voluntad (creencia que procede de Homero), y también al tránsito desde este mundo a otro mejor.

Distingue dos clases de conocimientos: los /sentidos/, que perciben las cosas corpóreas, particulares y mudables; y la /razón/, que conoce los conceptos universales.

** Física
No es posible reconstruir el concepto que Sócrates tenía del mundo. Desliga por completo la ciencia moral de la natural. Pero, aunque rechaza por inútiles y estériles las investigaciones cosmológicas de sus predecesores, puede vislumbrarse un concepto optimista del Universo.

** Teología
Platón y Jenofonte se esfuerzan por defender a Sócrates de la acusación de /asebeía/. Defendió los dioses de su ciudad. Pero admitió la existencia de un Dios único, supremo, ordenador del Mundo, aunque no creador. No está claro si habría que entenderlo en sentido personal, a la manera del Logos de Heráclito.

** Ética
Sócrates defiende una formulación utilitarista del bien. No hay "bien que no sea bien para alguna cosa". "Lo que es útil es bien para aquel que le es útil".

No logró rebasar el hedonismo y el relativismo. El bien es relativo, "lo que es bueno para el hambre, es malo para la fiebre; y lo que es bueno para la fiebre es malo para el hambre". Pero en este fondo hedonista Sócrates se esfuerza por someterlo a la razón. Defendiendo a ultranza la moderación.
