:PROPERTIES:
:ID:       555080BF-090C-4C9B-9BE1-DF23B8244EC8
:END:
#+title: Epicureísmo

Epicuro funda una escuela, el Jardín, pero que se separa de las formas de la paidea clásica. El objetivo de esta nueva escuela no será educar en cuanto a tal, sino establecer un modo de vida. Este modo de vida se puede resumir con el cartel que marcaba la entrada del jardin: *Vive retiradamente*.

Epicuro es antiplatónico y antiaristotélico.


* Crítica a Platón

La ética platónica se construye sobre la suposición de que las virtuades huamanas son naturales y preexisten a la construcción de la ciudad. De esta forma, las leyes de la ciudad deben formarse en imitación de estas leyes naturales. Epicuro defiende que es al revés, es por la existencia de la ciudad la que permite a las sociedades huamanas actuar en cojunto de forma civilizada. 

Tras la aparición de la nueva forma de gobierno macedónica, donde la capital de es una ciudad a menudo alejada y distante, Epicuro determinará que es posible multiples formar de eduación. Así se *sobrepasará la paideia clásica* determinando que, al no haber un conjunto de virtudes naturales que enseñar y aprender, podrán existir otras formas, igual de buenas, de educación.


* Crítica a los Cínicos

Epicuro, en contra de los cínicos cree que la vida virtuosa y feliz sí se haya el una comunidad humana.


* Dialéctica

Epicuro forma en las artes retóricas y poéticas un método de construcción de comunidades. A diferencia de Aristóteles no está interesado en una lógica demostrativa, pero sí entiende la utilidad de las herramientas retóricas.


* Comunidad de amigos

Finalmente, Epicuro encontrará esa comunidad necesariamente electiva, ya que no existe una mejor que otra per se, y útil para tener una vida virtuosa y feliz en una comunidad de amigos.

** Prescipciones para la vida virtuosa

*** No tener miedo a los dioses
El mundo helenístico donde las ciudades estado clásicas desaparecen es un mundo donde los dioses de la ciudad han, de alguna forma, fallado en su cometido.

*** No temer a la muerte
Aquí hayamos en Epicuro un argumento en contra del miedo a la muerte: nadie experimenta la muerte. Una vez se muere uno no es, por tanto, no hay simultaneidad entre uno mismo y su muerte.

*** Los placeres como criterio de elección
Si vivimos en comunidades libres y elegidas como escojemos nuestra comunidad, y con ella nuestro estilo de vida, pues en función de los placeres. Es importante enteder que los placeres Epicureos, a diferencia de los cirenaicos, en, principlamente, la ausencia de dolor.

