:PROPERTIES:
:ID: 08455BC0-0658-48BE-A747-27501969687D
:END:
#+title: 2. Spinoza

Spinoza sostiene una concepción neoplatónica de Dios, que lo llevará a defender la idea de Dios como sustancia única. Identifica Dios y naturaleza, llega al panteísmo. Hacer hincapié en la naturaleza necesaria de la existencia, prescindiendo de causas finales y las consideraciones teológicas.

Partiendo del dios panteísta que se identifica con la naturaleza y de la idea neoplatónica de la sustancia única, Spinoza formula su método gnoseológico partiendo de la idea de idea verdadera, a la cual tenemos acceso al ser innata a nosotros. El primer paso del método será conseguir llegar a esta idea verdadera, comprenderla y distinguirla de las otras percepciones, investigando su naturaleza. Esta idea a su vez, no depende de ningún criterio externo, debe de ser /index sui/, llevar en sí misma la marca de su verdad.

En este modelo de pensamiento, la razón percibe en acto la producción espontánea de ideas por su pensamiento, y ve como la verdad de esas ideas se impone a él por el hecho de que, produciéndolas él mismo, las capta interiormente en su génesis.

* Paralelismo lógico-metafísico
Una de las características más importantes y distintivas del método de Spinoza es la identificación entre el orden y conexión de las ideas (orden lógico) y el orden y conexión de las cosas (orden ontológico). Para Spinoza, la deducción lógica de conclusiones a partir de definiciones adecuadas es también una deducción metafísica que nos ofrece conocimiento de la realidad.

Este paralelismo supone una separación tanto de los escolásticos como de Descartes. En la filosofía de Santo Tomás se parte de los objetos sensibles para llegar a la idea de Dios, elevando la experiencia sensible, mediante la reflexión. Por otra parte, Descartes comienza por el /cogito ergo sum/, no por Dios. En ambos casos la primera idea en sentido lógico, es decir, el punto de partida del sistema filosófico, no es la primera idea en sentido ontológico, i.e. Dios.

En resumen, el sistema de Spinoza es claramente una teoría de la deducción.
