:PROPERTIES:
:ID: 27F848FD-DFD6-4BED-AF01-ED83EBDE083E
:END:
#+title: 3. Leibniz

Para Spinoza, la razón es la facultad que establece relaciones necesarias, mientras para Leibniz es la mera posibilidad de establecer relaciones. Para Leibniz, pues, la categoría principal para explicar la realidad no es la necesidad, sino la posibilidad. Lo que existe, para Leibniz, no es, como afirma Spinoza, una manifestación geométricamente necesaria de la esencia de Dios, sino sólo el resultado de una libre decisión suya.

* Monadología
Leibniz modifica la concepción cartesiana de la realidad como constituida por la extensión y el movimiento, sino que el elemento originario y constitutivo del mundo físico sería la fuerza. Motivando este cambio, en parte, por la fórmula de Newton que demuestra que la fuerza no es masa por velocidad, sino velocidad al cuadrado. Es decir, no se conserva la cantidad de movimiento de un sistema, sino la cantidad de fuerza motriz.

Por otra parte, motivado esta vez por el cálculo infinitesimal, Leibniz identificaría el componente principal de la realidad con el punto sustancial, principio activo y causa eficiente del movimiento. Este punto sustancial sería simple, sin partes, y se denominará mónada. Cada mónada creada representa el universo entero. La mónada sería como un átomo espiritual, unificando las dos partes del dualismo cartesiano.
