:PROPERTIES:
:ID: 7F4D83DA-8820-4365-9826-FEBED1E97486
:END:
#+title: 4. Gnoseología

* Conocimiento sensitivo
Toda la teoría aristotélica del conocimiento está concebida en sentido realista. En Aristóteles el conocimiento sensitivo se caracteriza por pasividad y receptividad de la potencia respecto de un objeto activo. El que siente, sufre una acción, un movimiento y una alteración orgánica. Los sentidos, al conocer, reciben en sí las formas de los objetos que actúan sobre ellos. Pero las reciben sin materia, a la manera de la cera que recibe la impresión de un anillo con total independencia de la materia, ya sea oro o bronce, del que este esté hecho.

Aristóteles distingue entre sentidos internos y externos. Los externos son cinco: vista, oído, gusto, tacto y olfato; y los internos son sentido común, imaginación, estimativa y memoria.

Los sentidos no perciben las esencias de las cosas, ni tampoco su forma sustancial, ni los seres en su entidad total. Solamente perciben las formas accidentales externas. Estos objetos de la sensación los distingue Aristóteles en dos clases: 1. /Sensibles propios/: que corresponden a los objetos propios y particulares de cada sentido externo: a la vista el color, al oído el sonido, al olfato el olor, etc. Cada sentido es afectado por una clase determinada de sensibles y no puede percibir el resto. 2. /Sensibles comunes/, que son aquellos cuya percepción no es exclusiva de ningún sentido determinado. Son la magnitud, la figura, el número, la unidad, la pluralidad, el movimiento y la quietud.

Los sentidos internos son:

1. /Sentido común/. Lo poseen todos los animales y es una suerte de facultad centralizadora de toda la red de percepciones sensibles dispersa. Tiene tres funciones, la percepción de sentidos comunes; la reflexiva, que dota al animal de conciencia de sí mismo como sujeto que percibe; y la de discernimiento, la comparación y la coordinación entre percepciones que perteneces a distintos sentidos, lo blanco y lo dulce, lo duro y lo oloroso.
2. Imaginación. Es un sentido interno superior al común, que solamente poseen los animales más perfectos. Su función es la de percibir y conservar las impresiones sensibles que llegan a través del sentido común, y reproducirlas en ausencia de los objetos que las han causado. La fantasía produce imágenes, que, a diferencia de las impresiones de los sentidos, pueden ser verdaderas o falsas.
3. Estimativa. Que permite discernir entre lo agradable y desagradable.
4. Memoria. Otro sentido interno que es capaz de conversar las impresiones sensoriales, pero a diferencia de la imaginación, se encarga de ordenarlas conformo a leyes de asociación.
5. Apetito. Junto con la sensibilidad cognoscitiva hay que distinguir otra de orden práctico. El animal, en virtud de los conocimientos suministrados por los sentidos, desea o aborrece, busca o rehúye, determinados objetos.

* Conocimiento intelectivo
En el libro /De anima/ Aristóteles aborda la cuestión del conocimiento intelectivo, estableciendo un paralelo con el conocimiento sensitivo, en virtud de su teoría del acto y de la potencia. De aquí resulta una doble función: una pasiva o receptiva y otra activa, a la que corresponde la elaboración de los inteligibles.

Esta noción se complica con la introducción de dos entendimientos, uno pasivo que /se hace/ a las cosas, y otro activo, que /hace/ las cosas.

El entendimiento pasivo es capaz de recibir las formas, está en potencia, no tiene mezcla ni está mezclado al cuerpo, es el receptáculo en potencia de las ideas, es separado del cuerpo, se hace cada uno de los inteligibles, es capaz de pensar a sí mismo, es simple, está en potencia para todos los inteligibles, es una tableta en la cual no hay nada escrito en acto, es corruptible y mortal.

A este contrapone Aristóteles el entendimiento activo, de categoría superior, cuya función es producir los inteligibles, obrando a la manera de la luz que pone en acto los colores que estaban en potencia, suministrando así el material cognoscitivo al entendimiento pasivo.
