:PROPERTIES:
:ID: B697717A-34E5-4661-8B33-1AE2690CF8EA
:END:
#+title: σ-algebra

Given an arbitrary set \(X\), and let \(\mathcal{P}(X)\) be its power set. Then a subset \(\Sigma \subset \mathcal{P}(X)\) is called a \(\sigma\)-algebra if and only if it satisfy the following: 1. \(X\) is in \(\Sigma\) 2. \(\Sigma\) is closed under complementation: If \(A \in \Sigma\), then \(X \backslash A \in \Sigma\). 3. \(\Sigma\) is closed under unions: If \(A_1, \dots, A_n \in \Sigma\), then \(A_1 \cup\dots\cup A_n \in \Sigma\).

From these properties, it follows that the σ-algebra is also closed under countable intersections.

An interesting property is that the intersection of a collection of σ-algebras is also a σ-algebra.

** σ-algebra generated by an arbitrary family
Let \(F\) be a family of subsets of \(X\). Then there exists a unique smallest σ-algebra which contains every set in \(F\). It is, in fact, the intersection of all σ-algebras containing \(F\).

*** Borel σ-sigma algebra
An important example is the [[id:35870FDB-C98B-4EA3-89D2-E3153FABF842][Borel algebra]] over any [[id:C0ADBA68-2416-4041-A4E8-E3F3778D9938][topological space]]: the σ-algebra generated by the open sets.
