:PROPERTIES:
:ID: C6FBEB0E-9555-4AA6-B64B-0D76D0941890
:END:
#+title: Fase Acrítica

* ¿Qué son las ideas?
A diferencia de la doctrina socrática de las ideas universales como aquello común entre las ideas particulares, conseguidas por vía de la inducción, para Platón las ideas son entes ontológicos a en sí mismo, que habitan el mundo inteligible.

Esta concepción cumple una doble función: 1. Garantizar a la ciencia un objeto apropiado de estudio. 2. Dar razón de ser de las cosas concretas del mundo sensitivo. Ya que en la visión platónica las cosas particulares dependen de las ideales (y no al revés como en la socrática): un cuerpo es bello en cuanto a que participa en la belleza ideal.

* Conocer es recordar
El alma es la única que puede acercarse al mundo de las ideas, del que proviene, para entenderlas y conocer la verdad. El mundo sensible, a través de los sentidos, ofrece al alma la oportunidad para recordar las ideas con las cuales estuvo previamente en contacto.

Para poder formular esta teoría del conocimiento, Platón recurre a la doctrina órfico-pitagórica sobre la eternidad e inmortalidad del alma. Esta olvidaría todo lo previamente aprendido al caer en la prisión del cuerpo, y iría recordándolo gracias al estímulo de los particulares a través de los sentidos.

** Grados de conocimiento
Platón amplía la teoría parmenída del conocimiento, en la que existen dos grandes niveles de conocimiento, la ciencia (/episteme/) y la opinión (/doxa/), admitiendo, a diferencia de Parménides, que el conocimiento basado en los sentidos puede ser cierto en cierto grado. Así Platón distingue entre:

1. Conocimiento sensible: aquel referido al mundo de las apariencias. No puede ofrecer una certeza científica firme sino sólo probabilidades, y, por tanto, es recaen mundo de lo opinable. Dentro de este se puede señalar dos grados: la conjetura y la creencia.
2. Conocimiento inteligible: referido al mundo de las ideas. También se distinguen dos grados, el razonamiento matemático y el dialéctico. Sirviendo el primero, más bien, como preparación al segundo.

Dentro de la razón, cabe distinguir entre la razón discursiva y la razón intuitiva. La primera se ocupa de los objetos matemáticos valiéndose de figuras imaginarias o reales de los objetos sensibles para llegar, a través de la hipótesis, a los inteligibles. Y la intuitiva correspondería para Platón con el mayor y más perfecto grado de conocimiento, pues consiste en contemplar las esencias de las cosas en sí mismas. Esta contemplación es proporcionada por la dialéctica, el método propio de la filosofía.

* La dialéctica
Al igual que para su maestro Sócrates, la dialéctica tiene para Platón, en un sentido general, el arte del diálogo. Aunque Platón engloba aquí todo pensamiento discursivo como diálogo del alma consigo misma. Por tanto, la dialéctica compondría el procedimiento propio del conocimiento racional.

A diferencia del razonamiento matemático, que es deductivo, la dialéctica sería una suerte de proceso de selección de las características que, en las cosas, permiten compararlas con sus modelos ideales.

* Características de esta etapa
En esta primera etapa acrítica, que se desarrollaría entre los primeros diálogos hasta el Fedón, encontramos gran varianza terminológica en como Platón se dirige a las ideas. Entre ellas contradicciones entre expresiones que indican la inmanencia y otras que indican la trascendencia de las Ideas. Además de un marcado realismo ontológico para las Ideas.
