:PROPERTIES:
:ID:       660B7F3B-F773-4B9E-A745-7E0F143C7313
:END:
#+title: Orfismo

* Mensaje del orfismo
** Mito de Dionísio y los Titanes

El mito de Dionísio comienza con el mito clásico del ascenso al poder de los distintos reyes de los dioses griegos. Primero Urano, el primer rey, tiene realaciones constantes con su mujer Gea para evitar la gestación. Finalmente Gea se pone de acuerdo con hijo Kronos para castrar a su padre y ocupar su lugar. Posteriormente, Kronos tratando de vitar el mismo destino que su padre devorada a sus hijos al nacer, hasta que su mujer Rea escondió a uno de sus descendientes, Zeus, que lo encerro en el Tártaro tras destronarle. Zeus, como último de la sucesión decide aceptar su denstino y otorgale el reinado de los dioses a su hijo Dionísio. Los titanes, celosos del hijo, lo engañan y lo desmienbran y comen. Zeus al conocer los hechos fulmina a los titanes con su rayo y de la sangre de los titanes y la tierra naceran los humanos.

De este origen mítico de los seres humanos se sigue su dualidad material y divina -dada esta segunda por su alma- al ser mezcla de la tierra y de la sangre de los dioses. También de aquí se sigue un crimen orignal, el de los titanes y explica la bondad del alma humana, que proviene de Dionísio y la maldad humana, que proviene de los titanes. Este crimen orignial se ha de expiar en vida, siendo de tal magnitud que se necesitan varias vidas, explicando la creencia orfíca en la transmigración de las almas.

** Consecuencias del mito

- Dualismo cuerpo y alma del ser humano.
- Dualdad moral, el bien proviene de Dioniso y el mal de los Titanes.
- La justicia como fundamento y la retribución en el más Allá.
- La transmigración como corolario de la inmortalidad y la necesidad de justicia.
- La soliraliedad entre los seres vivos.
