:PROPERTIES:
:ID:       A582A33E-1B75-438E-8242-0FD181498228
:END:
#+title: Metafísica aristotélica

* ¿Cuál es la Filosofía Primera?

** Primer proyecto de la metafísica: causas y principios

Este primer proyecto se basa en entender la ciencia primera como una fundamentalización de aquellas operaciones sin las cuales no tenemos conocimiento. Como se ha dicho en el apartado de epistemología, Aristóteles establece que se puede obtener un conocimiento unviersal cuando se señala que un fenómeno cualquiera se atiene a una causa que regularmente es siempre la misma o bien cuando se construye mediante la aplicación de un principio que también  sea siempre el mismo. Además y de nuevo, está es la única forma de saltarse la crítica escéptica, ya que el escéptico usará inevitablemente estas causas y principios en sus objeciones.

De está forma Aristóteles señala cuatro posibles causas y unas indicaciones a los posibles principios.

*** Causas
Como es conocido podemos declarar porque un fenómeno es materialmente así, porque es formalmente así, porque ha sido hecho o para que fin se ha hecho. Es importante ver estás causas no tienen necesariamente una correspondencia en la naturaleza, sino que pueden verse como un ejercicio ontopraxiológico, es la razón humana, el Nous el que preguntándose la pregunta concreta organiza ciertas características del objeto natural para responderse.

De está forma las cuatro causas conforman una trama, una red que cuando el Nous, el intelecto, la hecha sobre el mundo natural obtiene cierta imagen sobre como se conforma un objeto natural.

*** Principios
No existe una teoría exhaustiva de los principios como en el caso de las causas porque puedes usarse de forma independientes unos con respecto a otros. Sin embargo, *como en el caso de las causas han de ser entendidos desde como mecanismos de la inteligencia humana que operan sobre la naturaleza para desvelar sus estructuras más íntimas*. En este caso la estructura que se entablan no es causal, sino se usan para fundamentar el conocimiento.


*** Conclusiones de este primer proyecto

De está forma una axiomática es siempre una metafísica aristotélica. El matemático aristotélico por excelencia es Euclides.

Podemos ver que estos primeros principios y cuasas no son demostrados ni demostrables, sino que se presuponen motivados por las consecuencias ausentes de fecundidad y casi contradictorias de sus negaciones.


** Segundo proyecto de la metafísica: ¿Qué es el ser? Ontología o ciencia del ser en cuanto a ser

Tras establecer la retícula operativa y metodológica obtenemos una pregunta de continuación que es si estos primeros principios y estructuras causales que proyectamos sobre la naturaleza nos permites justificar el uso de los conceptos abstractos que obtenemos usando estos métodos.

Aristóteles señala tras intentar validar los conceptos abstractos en una teoría del ser que existen ciertos conceptos que no pueden predicarse. Esto es un corolario de la agrupación del sujeto en categorías. De esta forma, Aristóteles concluye que el ser se dice de varias maneras. Así ni el ser es unívoco ni multiple pero basado en lo que no es cada ser, como explicaba Platón. El ser Aristotélico será multiple, lo que permite una ontología o ciencia del ser.

Entonces, ¿de cuántos modos se puede decir el ser? Pues fundamentalmente dos, el ser puede decirse como sujeto o como predicado.

*** Acto y pontencia :important:

Uno de los problemos básicos que se encuntra la ontología que es aquel de constuituir un lenguaje enunciativo ontológico que o bien fija el ser para siempre una vez se dice o bien solo capta un instante fugaz del ser.

Para solventar este problema decimos que además de los dos modos básicos del ser, sujeto y predicado existen dos básicos estados del ser, el acto y la potencia.

- Acto: el acto es la realización del ser.
- Potencia: la potencia es la posibilidad del ser.

*Así, el esquema del acto y potencia sirve para solventar las críticas Eléatas al movimiento y suponen una continuación del ecosistema ontopraxiológico que Aristóteles plantea para poder decir la realidad.*


*** Jerarquía ontológica

Aristóteles establece que, aunque el ser se diga de varias maneras, es más importante el ser cuando se dice en la función del sujeto que cuando se dice en la función del predicado. Esta elección dará lugar a la _lógica predicativa_, aquella en la que lo que importa es el sujeto y que atributos le podemos asignar. Por otra parte, está elección no es necesaria, contraste, por ejemplo, con las filosofías budistas que priman las relacionas a los objetos. Está elcción es muestra de la deuda a Parménides.
  
** Tercer proyecto de la metafísica: ousología

Tras establecer los modos dinstintos de ser, que son varios, pero concluir que existe uno prominente más importante del resto llegamos a nuestro tercer proyecto para la metafíscia aristotélica, la ousología. Está teoría responderá a la pregunta que podemos sabre por esta forma eminente del ser.

*** Sobre la traducción latina de ousia

La traducción latina de ousia por substancia tiene sentido en el contexto de la física aristotélica, donde esta ousia es, efectivamente, el substrato subyacente que permite el movimiento sin romper la idea del ser. Es decir, la substancia en la física, es decir, en el contexto del movimiento, es aquello que permanece igual en un ente tras ser movido.

Sin embargo, para el contexto de la Filosofía Primera es mejor ir a la forma léxica del concepto y traducirlo simplemente por ente, auquello que es.

*** Materia y forma :important:

El esquema de materia y forma es el esquema propio de la ousología.

Existe en la metafísica aristotélica una primera materia sin forma, indeterminada que no puede tener predicados concretos. Posteriormente, existe materia con forma que ya permite caractéres atrbutivos. Así el ente será una mezcla entre materia y forma.

*Aristóteles establece la prioridad de la figura, de la forma sobre la materia. Así en la forma estará el inteligible, lo que cabe entenderse y explicarse de la realidad.* Así queda claro que la teoría aristotélica no es un materialismo.

La materia solo permite los predicados de cantidad y el resto recaen en la forma.

*La esencia es lo que era el ser*, la esencia es aquello que subsiste sobre cualquier diferenciación accidental. Así se trae el mundo platónico al físico.


** Cuarto proyecto de la metafísica: teología 

Al establecer la primacía de la forma nos queda una pregunta, ¿puede existir un ser puramente formal? La respuesta, al menos práctica, a esta pregunta es que debemos de tener en cuenta tales seres al experimentar en nuestro viaje científico la verdad de ciertos enunciados necesarios que, precisamente al ser necesarios, están desprovistos de cualquier componente contingente que trae consigo la materia.


*** Libro λ

De este racionamiento sumado a la jerarquización en función de motores en el mundo físico nos lleva al primer motor inmóvil, primera causa incausada. Esta conclusión, en conjunto con la descripción de este primer motor inmóvil como forma sin materia o acto puro sin potencia, se nos presenta en el libro lambda de la Metafísica que es bastante cuestionado. El libro lambda es útil porque propone una solución a muchos de los problemas metafísicos al permitir justificar una primacía de la necesidad sobre la contingencia.

Muchas de las críticas señalan que esta idea es una vuelta al mundo platónico.


*** Solución práctica

Si nos vamos a la forma opuesta de solucionar los problemas de la metafísica hayamos una solución propuesta en los libros anteriores, la de la acción. De alguna manera podemos resumir esta vía con el ejemplo de la visión. Una buena teoría de la visión consisten en una serie de enunciados que sean capades de describir y, quizás, de predecir los comportamiento de la visión, pero nunca podría permitirnos, por si sola, ver. De la misma forma, una buena teoría de una paideia musical que nos enseñe a tocar la lira deberá expresas en sus enunciados verdades sobre el instrumento y su arte pero no podrá hacer sonar el instrumento. Esto supone una vuelta a la visión ontopraxiológica.
