:PROPERTIES:
:ID: 64853E70-8C7D-44AF-B1C4-DFE3B3FCFABC
:END:
#+title: Information Theoretic Security

A cryptosystem is considered to have information theoretic security (ITS) if it is secure against adversaries with unlimited compute power and time.

In contrast, a system which depends on the computational cost of cryptanalysis to be secure (and thus can be broken by an attack with unlimited computation) is called computationally, or conditionally, secure.

There are a variety of cryptographic tasks for which information-theoretic security is a meaningful and useful requirement. A few of these are:

1. Secret sharing schemes such as [[id:F5AF9B91-7D2B-4C13-93CC-71B4E9C3E035][Shamir's]] information-theoretically secure (and also perfectly secure) in that having less than the requisite number of shares of the secret provides no information about the secret.
2. More generally, secure multiparty computation protocols often have information-theoretic security.
3. Information-theoretic cryptography is quantum-safe.
